log_util.py-do_log_msg-154-ERROR-some error occurs
log_util.py-do_log_msg-154:ERROR-some error occurs
log_util.py/do_log_msg-154:ERROR-some error occurs
